### ISSUE TITLE
Crashed while Rust was updating

### ISSUE THREAD

**Issue by egeexyz** [egee-irl/andro-wrcon#1]
Saved 26,960 ents, serialization(0.00), write(0.01), disk(0.27) totalstall(0.01).
Saving complete
Disconnected from Rust Server
Disconnected from Rust Server
/main.coffee:20
    return console.log(error).then(reoccuringErrors++);
                             ^
TypeError: Cannot read property 'then' of undefined
    at errorNotification (/main.coffee:12:3)
    at Array.<anonymous> (/main.coffee:28:29)
    at WebRcon.emit (/node_modules/webrconjs/webrcon.js:343:25)
    at WebRcon.onclose (/node_modules/webrconjs/webrcon.js:208:14)
    at WebSocket.onClose (/node_modules/ws/lib/WebSocket.js:446:14)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at WebSocket.cleanupWebsocketResources (/node_modules/ws/lib/WebSocket.js:950:8)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm info lifecycle andro-wrcon@1.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! andro-wrcon@1.0.0 start: `coffee -c -m main.coffee && coffee main.coffee`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the andro-wrcon@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-01T13_45_07_275Z-debug.log

**Comment by egeexyz** [comment]
Fixed by removing the ``.then`` from ``console.log()``. Not sure why it was there in the first place
