### ISSUE TITLE
Crashed while sending welcome message

### ISSUE THREAD

**Issue by egeexyz** [egee-irl/andro-wrcon#2]
Saving complete
/home/androgee/discordEvents.coffee:11
        return generalChannel.send(msg).then(console.log(msg)).catch(console.error);
                             ^
TypeError: Cannot read property 'send' of null
    at Client.<anonymous> (/home/androgee/discordEvents.coffee:6:21)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at Guild._addMember (/home/androgee/node_modules/discord.js/src/structures/Guild.js:1078:19)
    at GuildMemberAddHandler.handle (/home/androgee/node_modules/discord.js/src/client/websocket/packets/handlers/GuildMemberAdd.js:12:13)
    at WebSocketPacketManager.handle (/home/androgee/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/home/androgee/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (/home/androgee/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:17)
    at WebSocket.onMessage (/home/androgee/node_modules/discord.js/node_modules/ws/lib/EventTarget.js:99:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (/home/androgee/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/home/androgee/node_modules/discord.js/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/androgee/node_modules/discord.js/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/androgee/node_modules/discord.js/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/androgee/node_modules/discord.js/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/home/androgee/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:139:22)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at TLSSocket.Readable.push (_stream_readable.js:211:10)
    at TLSWrap.onread (net.js:587:20)
npm info lifecycle andro-wrcon@1.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! andro-wrcon@1.0.0 start: `coffee -c -m main.coffee && coffee main.coffee`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the andro-wrcon@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/androgee/.npm/_logs/2017-12-03T12_15_11_246Z-debug.log

**Comment by egeexyz** [comment]
Add a check for null until we have more info as to what exactly went wrong.

**Comment by egeexyz** [comment]
Using ``member.displayName`` seems to have fixed it
